### ISSUE TITLE
Error en Edit Profile

### ISSUE THREAD

**Issue by tanvirhosu** [kennyangelfib/PES_Fibness#11]
Si el usuario es nuevo y no tiene foto. Si entra en "edit profile" para cambiar algo excepto imagen, si da click en "done" entonces peta por la imagen (Bitmap).

EditProfileActivity.java
 protected void saveProfilePicture() {
        // Reading a Image file from file system
        //mirar que el bitmap no sea nulo
            Bitmap bitmap = ((BitmapDrawable) ivUser.getDrawable()).getBitmap();
            ByteArrayOutputStream baos = new ByteArrayOutputStream();
            bitmap.compress(Bitmap.CompressFormat.JPEG, 70, baos);
            byte[] imageInByte = baos.toByteArray();
            u.setImage(imageInByte);
            String response = baos.toString();
            //System.out.println("Respuesta Imagen: "+ response);
    }

creo que falta comprobar si Bitmap es nulo, como bien dice en los comentarios

**Comment by adbeje** [comment]
Ya esta solucionado, he llamado a la funcion justo despues de poner la imagen y así no da problemas en el caso de que se guarde el perfil con una imagen unseteada.
