### ISSUE TITLE
Error: estadistica

### ISSUE THREAD

**Issue by tanvirhosu** [kennyangelfib/PES_Fibness#13]
No puedo cargar la estadistica de un usuario. 
Sale un error del servidor "500 error"

**Comment by kennyangelfib** [comment]
Vale el error era que las migraciones a la base de datos del servidor no se han realizado bien , por lo cual la tabla estadisticas no se terminaba creando y el servidor trataba de acceder a ella pero le retornaba el error de que no esta no existia. Los cambios para solucionarlo fueron poner bien los nombre de las migraciones que hay en la base de datos.
