### ISSUE TITLE
Error a la hora de actualizar una ruta

### ISSUE THREAD

**Issue by adbeje** [kennyangelfib/PES_Fibness#5]
He visto que cuando intento **editar una ruta** acaba dando `server response error`. Creo que es problema de que el iterador que dice que ruta se tiene que editar no se pasa correctamente, habria que mirarlo.

**Comment by Pascual10** [comment]
Finalmente ha sido un problema al hacer merge. Faltaba una línea de codigo en la clase MapViewActivity que provocaba esto.
