### ISSUE TITLE
Error a la hora de actualizar la foto de perfil

### ISSUE THREAD

**Issue by adbeje** [kennyangelfib/PES_Fibness#7]
A la hora de actualizar una foto de perfil no sé porque cuando la subo a la base de datos y vuelvo a acceder a ella no me carga, me devuelve un objeto vacío, en local todo funciona perfectamente. Podrías mirar cual es el problema, ¿paso bien la fotografía a la BD? Aquí te dejo la función a ver si encuentras el error a la hora de hacer el **PUT** de la fotografía.
@kennyangelfib 

    public void setUserProfilePicture() {

        User u = User.getInstance();
        byte[] pic = u.getImage();
        final String data = Base64.encodeToString(pic, Base64.DEFAULT);

        request = new StringRequest(Request.Method.POST, this.urlAPI, new Response.Listener<String>() {
                @Override
                public void onResponse(String response) {

                    System.out.println("post response: " + response);
                    Toast.makeText(getApplicationContext(), "Your information has been modified", Toast.LENGTH_SHORT).show();
                }
            }, new Response.ErrorListener() {
                @Override
                public void onErrorResponse(VolleyError error) {
                    Toast.makeText(context, "Server Response error", Toast.LENGTH_LONG).show();
                }
            }) {
            @Override
            public String getBodyContentType(){
                return "image/jpeg";
            }
            @Override
            public byte[] getBody(){
                return data.getBytes(StandardCharsets.UTF_8);
            }
            };

        enqueue();
    }

**Comment by kennyangelfib** [comment]
El problema esta en el retorno del metodo **getBodyContentType** tendria que ser:

>  "image/jpeg; charset=utf-8"
El codigo de reemplazo seria:
```
@Override
            public String getBodyContentType(){
                return "image/jpeg; charset=utf-8";
            }
```
