### ISSUE TITLE
Error en desbloquar

### ISSUE THREAD

**Issue by tanvirhosu** [kennyangelfib/PES_Fibness#8]
El atributo "bloquado" de la ruta /user/id1/info/id2 no devuelve bien la respuesta, de si el usuario con id1 ha bloqueado a id2

**Comment by tanvirhosu** [comment]
He comunicado mal la petición, el atributo "bloqueado" tiene que devolver si el usuario con "id2" ha bloqueado a "id1"

**Comment by kennyangelfib** [comment]
Por lo visto doy el  bug por solucionado
